# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gs8H9aYgLysE4ql8VxdS6QyCBG442XJt
"""

from flask import Flask, render_template, request
import numpy as np
import pickle

app = Flask(__name__)
best_model_rf = pickle.load(open('best_model_rf.p', 'rb'))
monthly_charges_min, monthly_charges_max = 18.25, 219.0  
total_charges_min, total_charges_max = 8684.8, 18.8     
gender_map = {'male': 1, 'female': 0}
payment_method_map = {'Bank transfer': 0, 'Credit card': 1, 'Electronic check': 2, 'Mailed check': 3}
yes_no_map = {'yes': 1.0, 'no': 0.0}
multiple_lines_map = {'No': 0, 'Yes': 2}
@app.route('/')
def index():
    return render_template('input.html')
@app.route('/predict', methods=['POST'])
def predict():
    gender = gender_map[request.form['gender'].lower()]
    monthly_charges = (float(request.form['MonthlyCharges']) - monthly_charges_min) / (monthly_charges_max - monthly_charges_min)
    payment_method = payment_method_map[request.form['PaymentMethod']]
    paperless_billing = yes_no_map[request.form['PaperlessBilling'].lower()]
    senior_citizen = yes_no_map[request.form['SeniorCitizen'].lower()]
    phone_service = yes_no_map[request.form['PhoneService'].lower()]
    multiple_lines = multiple_lines_map[request.form.get('MultipleLines', 'No')]
    total_charges = (float(request.form['TotalCharges']) - total_charges_min) / (total_charges_max - total_charges_min)
    input_data = [
        gender,
        monthly_charges,
        payment_method,
        paperless_billing,
        senior_citizen,
        phone_service,
        multiple_lines,
        total_charges
    ]
    input_data = np.array([input_data])
    prediction = best_model_rf.predict(input_data)
    if prediction:
        value = 'Yes'
    else:
        value = 'No'
    return render_template('input.html', predicted_value=f'Customer Churn prediction is: {value} ')
if __name__ == '__main__':
    app.run(debug=True)

